class Constants(object):
    DEFAULT_SERVICE_HOST = "127.0.0.1"
    DEFAULT_SERVICE_PORT = 1337
    DEFAULT_IS_SECURE = False

    EXPORT_CONFIG_NAME_CHARTCONFIG = 'chartConfig'
    EXPORT_CONFIG_NAME_INPUTSVG = 'inputSVG'
    EXPORT_CONFIG_NAME_CALLBACK_FILE_PATH = 'callbackFilePath'
    EXPORT_CONFIG_NAME_DASHBOARD_LOGO = 'dashboardLogo'
    EXPORT_CONFIG_NAME_OUTPUT_FILE_DEFINITION = 'outputFileDefinition'
    EXPORT_CONFIG_NAME_TEMPLATE_FILE_PATH = 'templateFilePath'
    EXPORT_CONFIG_NAME_ASYNC_CAPTURE = 'asyncCapture'
    EXPORT_CONFIG_NAME_PAYLOAD = 'payload'
    EXPORT_CONFIG_NAME_TEMPLATE_FILE_PATH = "templateFilePath"
    EXPORT_CONFIG_NAME_TEMPLATE = "template"
    EXPORT_CONFIG_NAME_RESOURCE_FILE_PATH = "resourceFilePath"

    EXPORT_CONFIG_ZIP_PATH_INPUTSVG = "inputSVG.svg"
    EXPORT_CONFIG_ZIP_PATH_CALLBACK_FILE_PATH = "callbackFile.js"
    EXPORT_CONFIG_ZIP_PATH_DASHBOARD_LOGO = "dashboardLogo"
    EXPORT_CONFIG_ZIP_PATH_OUTPUT_FILE_DEFINITION = "outputFileDefinition.js"

    TEMPLATE_ZIP_PREFIX = "template"
    EXPORT_ZIP_FILE_NAME = "export.zip"
